### ISSUE TITLE
requires 'org.eclipse.equinox.p2.iu; org.eclipse.uml2.uml 0.0.0' but it could not be found

### ISSUE THREAD

**Issue by miksch27** [opendata-for-all/wapiml#26]

**Comment by miksch27** [comment]
Hi 
I tried to enable the plugin. At a first look at the reason,  I couldn't find an suitable answer...
Is my eclipse too up-to-date?  

Missing requirement: OpenAPI to UML 1.0.1.201906102017 (edu.uoc.som.openapitouml.feature.feature.group 1.0.1.201906102017) requires 'org.eclipse.equinox.p2.iu; org.eclipse.uml2.uml 0.0.0' but it could not be found

Thank you in advanced!

**Comment by hamzaed** [comment]
I'll take a look at that ASAP. In the meantime could you tell me which Eclipse version and distribution you're using? 

Thank you

**Comment by hamzaed** [comment]
We fixed the update site. Please let us know if you still have problems.

**Comment by miksch27** [comment]
Well, thank you I could install it, with out an error!  I use eclipse 06-2019. Thank you!

**Comment by miksch27** [comment]
Hi Hamzaed, I installed Eclipse IDE 06-2019, I installed 1.0.0.201907041706 id=edu.uoc.som.wapiml.feature.feature..  thank you the error is gone. I pass over this step
