### ISSUE TITLE
object instance has properties which are not allowed by the schema

### ISSUE THREAD

**Issue by nicostubi** [opendata-for-all/wapiml#46]
Hello,

I got this error:

![image](https://github.com/opendata-for-all/wapiml/assets/47106274/a01cf591-12f3-485c-95b9-e24350df9b20)

when trying to generate a class diagram for this [specification](https://docs.partner-api.monta.com/openapi/64f090e85ab6510044977858)

BR
Nicolas

**Comment by jlcanovas** [comment]
Hi @nicostubi, 

sorry for the late response, as you may have thought, this project is no longer maintained. The main developer is not working with us anymore and we don't have enough workforce to check your issue (any help is welcome!). 

I'll close the issue and also archive the project to move to read-only status. 

Thanks anyway!
